.TH "bin Directory Reference" 3 "Wed Apr 13 2016" "An Inexpensive, Software-Defined IF Modulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bin Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBbbftest\fP"
.br
.ti -1c
.RI "file \fBlsbftest\fP"
.br
.ti -1c
.RI "file \fBmodtest\fP"
.br
.ti -1c
.RI "file \fBmsintest\fP"
.br
.ti -1c
.RI "file \fBpltest\fP"
.br
.ti -1c
.RI "file \fBradio\fP"
.br
.ti -1c
.RI "file \fBsintest\fP"
.br
.ti -1c
.RI "file \fBusbftest\fP"
.br
.in -1c
