.TH "src Directory Reference" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBalsa_test\&.cpp\fP"
.br
.RI "\fITests sinusoidal tone generation\&. \fP"
.ti -1c
.RI "file \fBbaseband_filter_test\&.cpp\fP"
.br
.RI "\fITests sinusoidal tone generation\&. \fP"
.ti -1c
.RI "file \fBdefinitions\&.hpp\fP"
.br
.RI "\fIContains declarations of system-independant (universal size) integers and float types, shortened type names for some commonly used types, and enumerations\&. \fP"
.ti -1c
.RI "file \fBfft_test\&.cpp\fP"
.br
.RI "\fITests FFT, IFFT, and Hilbert implementations\&. \fP"
.ti -1c
.RI "file \fBfft_test2\&.cpp\fP"
.br
.RI "\fITests FFT, IFFT, and Hilbert implementations in \fBzdomain\&.hpp\fP\&. \fP"
.ti -1c
.RI "file \fBFilter\&.hpp\fP"
.br
.RI "\fIDefines the Filter class\&. \fP"
.ti -1c
.RI "file \fBfvectors\&.hpp\fP"
.br
.RI "\fIDefines the transfer function coefficients used in the instances of the Filter class in this program\&. \fP"
.ti -1c
.RI "file \fBiq_test\&.cpp\fP"
.br
.RI "\fIGenerates test IQ signal\&. \fP"
.ti -1c
.RI "file \fBmic_test\&.cpp\fP"
.br
.RI "\fITests getting mic input via ALSA  May not even compile at the moment\&. \fP"
.ti -1c
.RI "file \fBmodulation\&.hpp\fP"
.br
.RI "\fIContains the classes for the various types of modulation supported by the program\&. \fP"
.ti -1c
.RI "file \fBZDomain\&.hpp\fP"
.br
.RI "\fIThis is an abandoned, overly complicated attempt to have a class housing z-domain functions\&. \fP"
.ti -1c
.RI "file \fBzdomain\&.hpp\fP"
.br
.RI "\fIContains the functions to manipulate sequential data in the frequency (z) domain\&. \fP"
.in -1c
