.TH "src/auxiliary.hpp" 3 "Sun Apr 3 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/auxiliary.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'definitions\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBradio\fP"
.br
.RI "\fIcontains helper-functions for \fBmain()\fP \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBradio::ShowHelp\fP ()"
.br
.ti -1c
.RI "ModulationType \fBradio::to_type\fP (std::string str)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
