.TH "src/auxiliary.hpp" 3 "Wed Apr 13 2016" "An Inexpensive, Software-Defined IF Modulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/auxiliary.hpp \- 
.PP
Contains helper-functions for \fBmain()\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <climits>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <stdexcept>\fP
.br
\fC#include <string>\fP
.br
\fC#include 'definitions\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBradio\fP"
.br
.RI "\fIContains the classes for the various types of modulation supported by the program\&. \fP"
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBradio::ShowHelp\fP ()"
.br
.ti -1c
.RI "void \fBradio::to_sint32\fP (\fBfloat32\fP *data, \fBuint32\fP size)"
.br
.ti -1c
.RI "ModulationType \fBradio::to_type\fP (std::string str)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains helper-functions for \fBmain()\fP\&. 


.PP
\fBAuthor:\fP
.RS 4
Samuel Andrew Wisner, awisner94@gmail.com 
.RE
.PP

.PP
Definition in file \fBauxiliary\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for An Inexpensive, Software-Defined IF Modulator from the source code\&.
