.TH "src/baseband_filter_test.cpp" 3 "Sat Mar 5 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/baseband_filter_test.cpp \- 
.PP
Tests sinusoidal tone generation\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include 'definitions\&.hpp'\fP
.br
\fC#include 'Filter\&.hpp'\fP
.br
\fC#include 'fvectors\&.hpp'\fP
.br
\fC#include 'zdomain\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Tests sinusoidal tone generation\&. 


.PP
\fBAuthor:\fP
.RS 4
Samuel Andrew Wisner, awisner94@gmail.com 
.RE
.PP

.PP
Definition in file \fBbaseband_filter_test\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main ()"
This prgram tests and demonstrates the Filter class and the baseband low-pass filter (fp = 1\&.7 kHz, fs = 3 kHz, Ap = 0\&.5 dB, As = 60 dB)\&. 
.PP
Definition at line 24 of file baseband_filter_test\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
