.TH "bin/bbftest" 3 "Wed Apr 13 2016" "An Inexpensive, Software-Defined IF Modulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bin/bbftest \- 
Runs test on the baseband filter\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Runs test on the baseband filter\&. 


.PP
\fBAuthor:\fP
.RS 4
Samuel Andrew Wisner, awisner94@gmail.com 
.RE
.PP

.PP
Definition in file \fBbbftest\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for An Inexpensive, Software-Defined IF Modulator from the source code\&.
