.TH "bug" 3 "Wed Apr 13 2016" "An Inexpensive, Software-Defined IF Modulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
bug \- Bug List 

.IP "\fBFile \fBalsa_test\&.cpp\fP \fP" 1c
Clicking noise from sinusoidal discontinuity  
.IP "\fBFile \fBFilter\&.hpp\fP \fP" 1c
Discontinuities created at the beginning of each pass  
.IP "\fBFile \fBlsb_filter_test\&.cpp\fP \fP" 1c
Clicking occurs at start of each filter pass  
.IP "\fBFile \fBModulator\&.hpp\fP \fP" 1c
Both FM modulations don't work 
.PP
Clicking on the filtered SSB  
.IP "\fBFile \fBmodulator_test\&.cpp\fP \fP" 1c
Filtered SSB clicking  
.IP "\fBFile \fBusb_filter_test\&.cpp\fP \fP" 1c
Clicking occurs at start of each filter pass 
.PP

