.TH "src/definitions.hpp" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/definitions.hpp \- 
.PP
Contains declarations of system-independant (universal size) integers and float types, shortened type names for some commonly used types, and enumerations\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <complex>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBradio\fP"
.br
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBENUM\fP   signed char"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef unsigned char \fBbyte\fP"
.br
.ti -1c
.RI "typedef unsigned char \fBuint8\fP"
.br
.ti -1c
.RI "typedef signed char \fBsint8\fP"
.br
.ti -1c
.RI "typedef unsigned short \fBuint16\fP"
.br
.ti -1c
.RI "typedef signed short \fBsint16\fP"
.br
.ti -1c
.RI "typedef unsigned int \fBuint32\fP"
.br
.ti -1c
.RI "typedef signed int \fBsint32\fP"
.br
.ti -1c
.RI "typedef unsigned long long \fBuint64\fP"
.br
.ti -1c
.RI "typedef signed long long \fBsint64\fP"
.br
.ti -1c
.RI "typedef float \fBfloat32\fP"
.br
.ti -1c
.RI "typedef double \fBfloat64\fP"
.br
.ti -1c
.RI "typedef std::complex< \fBfloat32\fP > \fBcfloat32\fP"
.br
.ti -1c
.RI "typedef std::vector
.br
< std::vector< \fBfloat32\fP > > \fBfparams\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBradio::Age\fP { \fBradio::OLD\fP, \fBradio::NEW\fP }"
.br
.ti -1c
.RI "enum \fBradio::Fractional\fP { \fBradio::NUM\fP, \fBradio::DEN\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains declarations of system-independant (universal size) integers and float types, shortened type names for some commonly used types, and enumerations\&. 


.PP
\fBAuthor:\fP
.RS 4
Samuel Andrew Wisner, awisner94@gmail.com 
.RE
.PP

.PP
Definition in file \fBdefinitions\&.hpp\fP\&.
.SH "Macro Definition Documentation"
.PP 
.SS "#define ENUM   signed char"

.PP
Definition at line 14 of file definitions\&.hpp\&.
.SH "Typedef Documentation"
.PP 
.SS "typedef unsigned char \fBbyte\fP"

.PP
Definition at line 16 of file definitions\&.hpp\&.
.SS "typedef std::complex<\fBfloat32\fP> \fBcfloat32\fP"
Defines a type for complex float32's\&. 
.PP
Definition at line 35 of file definitions\&.hpp\&.
.SS "typedef float \fBfloat32\fP"

.PP
Definition at line 29 of file definitions\&.hpp\&.
.SS "typedef double \fBfloat64\fP"

.PP
Definition at line 30 of file definitions\&.hpp\&.
.SS "typedef std::vector<std::vector<\fBfloat32\fP> > \fBfparams\fP"
Defines a type for the filter coefficients\&. 
.PP
Definition at line 40 of file definitions\&.hpp\&.
.SS "typedef signed short \fBsint16\fP"

.PP
Definition at line 21 of file definitions\&.hpp\&.
.SS "typedef signed int \fBsint32\fP"

.PP
Definition at line 24 of file definitions\&.hpp\&.
.SS "typedef signed long long \fBsint64\fP"

.PP
Definition at line 27 of file definitions\&.hpp\&.
.SS "typedef signed char \fBsint8\fP"

.PP
Definition at line 18 of file definitions\&.hpp\&.
.SS "typedef unsigned short \fBuint16\fP"

.PP
Definition at line 20 of file definitions\&.hpp\&.
.SS "typedef unsigned int \fBuint32\fP"

.PP
Definition at line 23 of file definitions\&.hpp\&.
.SS "typedef unsigned long long \fBuint64\fP"

.PP
Definition at line 26 of file definitions\&.hpp\&.
.SS "typedef unsigned char \fBuint8\fP"

.PP
Definition at line 17 of file definitions\&.hpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
