.TH "src/fft_test2.cpp" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/fft_test2.cpp \- 
.PP
Tests FFT, IFFT, and Hilbert implementations in \fBzdomain\&.hpp\fP\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <complex>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include 'definitions\&.hpp'\fP
.br
\fC#include 'zdomain\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Tests FFT, IFFT, and Hilbert implementations in \fBzdomain\&.hpp\fP\&. 


.PP
\fBAuthor:\fP
.RS 4
Samuel Andrew Wisner, awisner94@gmail.com 
.RE
.PP

.PP
Definition in file \fBfft_test2\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main ()"
This program tests the \fBfft()\fP, \fBifft()\fP, and \fBhilbert()\fP functions in the \fBzdomain\&.hpp\fP file\&.
.PP
This code is based on code from http://rosettacode.org/wiki/Fast_Fourier_transform#C.2B.2B\&. 
.PP
Definition at line 22 of file fft_test2\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
