.TH "src/fvectors.hpp" 3 "Wed Apr 13 2016" "An Inexpensive, Software-Defined IF Modulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/fvectors.hpp \- 
.PP
Defines the transfer function coefficients used in the instances of the Filter class in this program\&. The coefficients are listed by greatest order to least\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include 'definitions\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBradio\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBfparams\fP \fBradio::F_BASEBAND\fP"
.br
.ti -1c
.RI "\fBfparams\fP \fBradio::F_LOWERSIDEBAND\fP"
.br
.ti -1c
.RI "\fBfparams\fP \fBradio::F_UPPERSIDEBAND\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines the transfer function coefficients used in the instances of the Filter class in this program\&. The coefficients are listed by greatest order to least\&. 


.PP
\fBAuthor:\fP
.RS 4
Samuel Andrew Wisner, awisner94@gmail.com 
.RE
.PP

.PP
Definition in file \fBfvectors\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for An Inexpensive, Software-Defined IF Modulator from the source code\&.
