.TH "src/fvectors.hpp" 3 "Tue Mar 22 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/fvectors.hpp \- 
.PP
Defines the transfer function coefficients used in the instances of the Filter class in this program\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include 'definitions\&.hpp'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBradio\fP"
.br
.RI "\fIcontains helper-functions for \fBmain()\fP \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBfparams\fP \fBradio::F_BASEBAND\fP"
.br
.ti -1c
.RI "\fBfparams\fP \fBradio::F_LOWERSIDEBAND\fP"
.br
.ti -1c
.RI "\fBfparams\fP \fBradio::F_UPPERSIDEBAND\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Defines the transfer function coefficients used in the instances of the Filter class in this program\&. 


.PP
\fBAuthor:\fP
.RS 4
Samuel Andrew Wisner, awisner94@gmail.com 
.RE
.PP

.PP
Definition in file \fBfvectors\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
