.TH "src/iq_test.cpp" 3 "Tue Mar 22 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/iq_test.cpp \- 
.PP
Generates test IQ signal\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include 'zdomain\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Generates test IQ signal\&. 


.PP
\fBAuthor:\fP
.RS 4
Samuel Andrew Wisner, awisner94@gmail.com 
.RE
.PP

.PP
Definition in file \fBiq_test\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main ()"
This small program demonstrates the IQ generation abilities of the \fBmakeIQ()\fP function\&. 
.PP
Definition at line 20 of file iq_test\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
