.TH "src/iq_test.cpp" 3 "Wed Apr 13 2016" "An Inexpensive, Software-Defined IF Modulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/iq_test.cpp \- 
.PP
Generates test IQ signal\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include 'zdomain\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Generates test IQ signal\&. 


.PP
\fBAuthor:\fP
.RS 4
Samuel Andrew Wisner, awisner94@gmail.com 
.RE
.PP

.PP
Definition in file \fBiq_test\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main ()"
This small program demonstrates the IQ generation abilities of the \fBmakeIQ()\fP function\&. 
.PP
Definition at line 20 of file iq_test\&.cpp\&.
.PP
.nf
20            {
21     const uint16 len = 16384;
22     float32 data[len];
23     float32 iqData[2*len];
24 
25     for(int i = 0; i < len; i++) {
26         data[i] = sin(2*3\&.141592*170*i/len);
27     }
28 
29     while(true) {
30         read(STDIN_FILENO, &data, len * sizeof(float32));
31         makeIQ(data, iqData, len);
32         write(STDOUT_FILENO, &iqData,  2 * len * sizeof(float32));
33     }
34 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for An Inexpensive, Software-Defined IF Modulator from the source code\&.
