.TH "src/lsb_filter_test.cpp" 3 "Sun Apr 3 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/lsb_filter_test.cpp \- 
.PP
contains a program to test the LSB-via-filter implementation  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include 'definitions\&.hpp'\fP
.br
\fC#include 'Filter\&.hpp'\fP
.br
\fC#include 'fvectors\&.hpp'\fP
.br
\fC#include 'zdomain\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
contains a program to test the LSB-via-filter implementation 


.PP
\fBAuthor:\fP
.RS 4
Samuel Andrew Wisner, awisner94@gmail.com 
.RE
.PP

.PP
Definition in file \fBlsb_filter_test\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main ()"
Tests an implementation of LSB modulation through a filter\&. 
.PP
Definition at line 23 of file lsb_filter_test\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
