.TH "makefile" 3 "Sun Apr 10 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
makefile \- 
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
