.TH "makefile" 3 "Wed Apr 13 2016" "An Inexpensive, Software-Defined IF Modulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
makefile \- 
.PP
Contains recipes to compile the main program and the tests programs as well as making documentation and counting total lines of code in src/\&.  

.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Contains recipes to compile the main program and the tests programs as well as making documentation and counting total lines of code in src/\&. 


.PP
\fBAuthor:\fP
.RS 4
Samuel Andrew Wisner, awisner94@gmail.com 
.RE
.PP

.PP
Definition in file \fBmakefile\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for An Inexpensive, Software-Defined IF Modulator from the source code\&.
