.TH "src/mic_test.cpp" 3 "Wed Apr 13 2016" "An Inexpensive, Software-Defined IF Modulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/mic_test.cpp \- 
.PP
Tests getting mic input via ALSA\&.  May not even compile at the moment\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <cmath>\fP
.br
\fC#include <climits>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <alsa/asoundlib\&.h>\fP
.br
\fC#include 'definitions\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Tests getting mic input via ALSA\&.  May not even compile at the moment\&. 


.PP
\fBAuthor:\fP
.RS 4
Samuel Andrew Wisner, awisner94@gmail.com 
.RE
.PP

.PP
Definition in file \fBmic_test\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main ()"
This program tests taking information from the microphone via the ALSA API\&. Not sure if it works\&. 
.PP
Definition at line 21 of file mic_test\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for An Inexpensive, Software-Defined IF Modulator from the source code\&.
