.TH "src/modulator_test.cpp" 3 "Wed Apr 13 2016" "An Inexpensive, Software-Defined IF Modulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/modulator_test.cpp \- 
.PP
Contains a test program to test the Modulator class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <cstdio>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include 'auxiliary\&.hpp'\fP
.br
\fC#include 'Modulator\&.hpp'\fP
.br
\fC#include 'Sinusoid\&.hpp'\fP
.br
\fC#include 'PlTone\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains a test program to test the Modulator class\&. 


.PP
\fBAuthor:\fP
.RS 4
Samuel Andrew Wisner, awisner94@gmail.com 
.RE
.PP
\fBBug\fP
.RS 4
Filtered SSB clicking 
.RE
.PP

.PP
Definition in file \fBmodulator_test\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main (intargc, char *argv[])"
Program to test the Modulator class\&. 
.PP
Definition at line 25 of file modulator_test\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for An Inexpensive, Software-Defined IF Modulator from the source code\&.
