.TH "src/modulation.hpp" 3 "Mon Feb 15 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/modulation.hpp \- 
.PP
Contains the classes for the various types of modulation supported by the program\&.  

.SH SYNOPSIS
.br
.PP
\fC#include <array>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'definitions\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBradio::Modulator\fP"
.br
.ti -1c
.RI "class \fBradio::DsbLcModulator\fP"
.br
.ti -1c
.RI "class \fBradio::DsbScModulator\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBradio\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains the classes for the various types of modulation supported by the program\&. 


.PP
\fBAuthor:\fP
.RS 4
Samuel Andrew Wisner, awisner94@gmail.com 
.RE
.PP

.PP
Definition in file \fBmodulation\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
