.TH "src/Modulator.hpp" 3 "Tue Mar 22 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/Modulator.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <array>\fP
.br
\fC#include <cmath>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'definitions\&.hpp'\fP
.br
\fC#include 'Filter\&.hpp'\fP
.br
\fC#include 'fvectors\&.hpp'\fP
.br
\fC#include 'Sinusoid\&.hpp'\fP
.br
\fC#include 'zdomain\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBradio::Modulator\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBradio\fP"
.br
.RI "\fIcontains helper-functions for \fBmain()\fP \fP"
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const \fBuint32\fP \fBradio::FREQ_INTERMEDIATE\fP = 20000"
.br
.ti -1c
.RI "const \fBuint32\fP \fBradio::SAMPLING_RATE\fP = 48000"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
