.TH "src/multi_sinusoid_test.cpp" 3 "Sun Apr 10 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/multi_sinusoid_test.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cstdio>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include <vector>\fP
.br
\fC#include 'auxiliary\&.hpp'\fP
.br
\fC#include 'definitions\&.hpp'\fP
.br
\fC#include 'Sinusoid\&.hpp'\fP
.br
\fC#include 'zdomain\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int main (intargc, char *argv[])"
Program to test the Sinusoid class and demonstrate the frequency range of the sound card\&. 
.PP
Definition at line 26 of file multi_sinusoid_test\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
