.TH "src/piped_test.cpp" 3 "Wed Apr 13 2016" "An Inexpensive, Software-Defined IF Modulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/piped_test.cpp \- 
.PP
containts the original program used to test the piping-in idea  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include 'Filter\&.hpp'\fP
.br
\fC#include 'modulation\&.hpp'\fP
.br
\fC#include 'zdomain\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
containts the original program used to test the piping-in idea 


.PP
\fBAuthor:\fP
.RS 4
Samuel Andrew Wisner, awisner94@gmail.com 
.RE
.PP

.PP
Definition in file \fBpiped_test\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main ()"
Program originally used to test whether baseband audio could be piped into the program in real time\&. 
.PP
Definition at line 22 of file piped_test\&.cpp\&.
.PP
.nf
22            {
23     const uint16 len = 16384;
24     float32 data[len];
25     float32 iqData[2*len];
26 
27     while(true) {
28         read(STDIN_FILENO, &data, len * sizeof(float32));
29         makeIQ(data, iqData, len);
30         write(STDOUT_FILENO, &iqData,  2 * len * sizeof(float32));
31     }
32 
33 }
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for An Inexpensive, Software-Defined IF Modulator from the source code\&.
