.TH "src/piped_test.cpp" 3 "Sun Apr 10 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/piped_test.cpp \- 
.PP
containts the original program used to test the piping-in idea  

.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <cstdio>\fP
.br
\fC#include <unistd\&.h>\fP
.br
\fC#include 'Filter\&.hpp'\fP
.br
\fC#include 'modulation\&.hpp'\fP
.br
\fC#include 'zdomain\&.hpp'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
containts the original program used to test the piping-in idea 


.PP
\fBAuthor:\fP
.RS 4
Samuel Andrew Wisner, awisner94@gmail.com 
.RE
.PP

.PP
Definition in file \fBpiped_test\&.cpp\fP\&.
.SH "Function Documentation"
.PP 
.SS "int main ()"
Program originally used to test whether baseband audio could be piped into the program in real time\&. 
.PP
Definition at line 22 of file piped_test\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
