.TH "src/PlTone.hpp" 3 "Sun Apr 10 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/PlTone.hpp \- 
.PP
contains the PlTone class  

.SH SYNOPSIS
.br
.PP
\fC#include 'definitions\&.hpp'\fP
.br
\fC#include 'Sinusoid\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBradio::PlTone\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBradio\fP"
.br
.RI "\fIcontains helper-functions for \fBmain()\fP \fP"
.in -1c
.SH "Detailed Description"
.PP 
contains the PlTone class 


.PP
\fBAuthor:\fP
.RS 4
Samuel Andrew Wisner, awisner94@gmail.com 
.RE
.PP

.PP
Definition in file \fBPlTone\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
