.TH "src/PlTone.hpp" 3 "Wed Apr 13 2016" "An Inexpensive, Software-Defined IF Modulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/PlTone.hpp \- 
.PP
Contains the PlTone class\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'definitions\&.hpp'\fP
.br
\fC#include 'Sinusoid\&.hpp'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBradio::PlTone\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI " \fBradio\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Contains the PlTone class\&. 


.PP
\fBAuthor:\fP
.RS 4
Samuel Andrew Wisner, awisner94@gmail.com 
.RE
.PP

.PP
Definition in file \fBPlTone\&.hpp\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for An Inexpensive, Software-Defined IF Modulator from the source code\&.
