.TH "radio::Sinusoid" 3 "Wed Apr 13 2016" "An Inexpensive, Software-Defined IF Modulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
radio::Sinusoid \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Sinusoid\&.hpp>\fP
.PP
Inherited by \fBradio::PlTone\fP\fC [private]\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSinusoid\fP (\fBfloat32\fP \fBfrequency\fP, \fBuint32\fP \fBsamplingRate\fP=48000)"
.br
.ti -1c
.RI "\fB~Sinusoid\fP ()"
.br
.ti -1c
.RI "\fBfloat32\fP \fBnext\fP ()"
.br
.ti -1c
.RI "\fBfloat32\fP \fBnextShifted\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBfloat32\fP \fBfrequency\fP"
.br
.ti -1c
.RI "\fBuint32\fP \fBsinIndex\fP = 0"
.br
.ti -1c
.RI "\fBuint32\fP \fBsinIndexShifted\fP = 0"
.br
.ti -1c
.RI "\fBuint32\fP \fBsamplingRate\fP"
.br
.ti -1c
.RI "\fBfloat32\fP * \fBsinusoid\fP"
.br
.ti -1c
.RI "\fBfloat32\fP * \fBsinusoidShift90\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class creates an easy-to-call pair of sinusoids, pi/2 radians out of phase with each other, that will preserve its phase throughout its lifespan\&. Essentially, it is a ring buffer\&. 
.PP
Definition at line 21 of file Sinusoid\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "radio::Sinusoid::Sinusoid (\fBfloat32\fPfrequency, \fBuint32\fPsamplingRate = \fC48000\fP)"
Creates two ring-buffer sinusoids\&. 
.PP
Definition at line 78 of file Sinusoid\&.hpp\&.
.SS "radio::Sinusoid::~Sinusoid ()"
Frees arrays malloc'ed in the constructor\&. 
.PP
Definition at line 93 of file Sinusoid\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBfloat32\fP radio::Sinusoid::next ()"
Provides the next value of the sinusoid in a manner consistant with a ring buffer\&. 
.PP
Definition at line 98 of file Sinusoid\&.hpp\&.
.SS "\fBfloat32\fP radio::Sinusoid::nextShifted ()"
Provides the next value of the shifted sinusoid in a manner consistant with a ring buffer\&. 
.PP
Definition at line 103 of file Sinusoid\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBfloat32\fP radio::Sinusoid::frequency\fC [protected]\fP"
The frequency of the sinusoid\&. 
.PP
Definition at line 49 of file Sinusoid\&.hpp\&.
.SS "\fBuint32\fP radio::Sinusoid::samplingRate\fC [protected]\fP"
The sampling rate\&. 
.PP
Definition at line 64 of file Sinusoid\&.hpp\&.
.SS "\fBuint32\fP radio::Sinusoid::sinIndex = 0\fC [protected]\fP"
The current index of the sinusoid's unshifted array\&. 
.PP
Definition at line 54 of file Sinusoid\&.hpp\&.
.SS "\fBuint32\fP radio::Sinusoid::sinIndexShifted = 0\fC [protected]\fP"
The current index of the shifted sinusoid's array\&. 
.PP
Definition at line 59 of file Sinusoid\&.hpp\&.
.SS "\fBfloat32\fP* radio::Sinusoid::sinusoid\fC [protected]\fP"
Initialized as an array of the sinusoid values\&. 
.PP
Definition at line 69 of file Sinusoid\&.hpp\&.
.SS "\fBfloat32\fP* radio::Sinusoid::sinusoidShift90\fC [protected]\fP"
Initialized as an array of the sinusoid values shifted 90 degrees\&. 
.PP
Definition at line 75 of file Sinusoid\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for An Inexpensive, Software-Defined IF Modulator from the source code\&.
