.TH "radio::PlTone" 3 "Wed Apr 13 2016" "An Inexpensive, Software-Defined IF Modulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
radio::PlTone \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <PlTone\&.hpp>\fP
.PP
Inherits \fBradio::Sinusoid\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPlTone\fP (\fBfloat32\fP amplitude, \fBfloat32\fP *data, \fBuint32\fP size, \fBfloat32\fP \fBfrequency\fP, \fBuint32\fP \fBsamplingRate\fP=48000)"
.br
.ti -1c
.RI "void \fBAdd\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class creates a PL tone (CTCSS tone) at a specified frequency in a baseband signal\&. 
.PP
Definition at line 18 of file PlTone\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "radio::PlTone::PlTone (\fBfloat32\fPamplitude, \fBfloat32\fP *data, \fBuint32\fPsize, \fBfloat32\fPfrequency, \fBuint32\fPsamplingRate = \fC48000\fP)"
Creates a \fBPlTone\fP object\&.
.PP
\fBParameters:\fP
.RS 4
\fIamplitude\fP the amplitude (0-1) of the subcarrier\&. Assumes baseband signal has a peak-to-peak range of -1 to 1\&.
.br
\fIdata\fP an array containing a portion of the discrete baseband signal
.br
\fIsize\fP the number of elemeents in the data array
.br
\fIfrequency\fP the frequency of the CTCSS tone in the baseband (not in the IF or RF signals)
.br
\fIsamplingRate\fP the sampling frequency of the baseband signal 
.RE
.PP

.PP
Definition at line 63 of file PlTone\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void radio::PlTone::Add ()"
Adds the PL tone to the baseband signal\&. 
.PP
Definition at line 75 of file PlTone\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for An Inexpensive, Software-Defined IF Modulator from the source code\&.
