.TH "radio::Filter" 3 "Wed Apr 13 2016" "An Inexpensive, Software-Defined IF Modulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
radio::Filter \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <Filter\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFilter\fP (\fBfloat32\fP *\fBdata\fP, \fBuint32\fP \fBsize\fP, \fBfparams\fP &\fBdiffEq\fP)"
.br
.ti -1c
.RI "void \fBPass\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBuint8\fP \fBeqLength\fP"
.br
.ti -1c
.RI "\fBuint32\fP \fBsize\fP"
.br
.ti -1c
.RI "\fBfloat32\fP * \fBdata\fP"
.br
.ti -1c
.RI "\fBfparams\fP \fBdiffEq\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 31 of file Filter\&.hpp\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "radio::Filter::Filter (\fBfloat32\fP *data, \fBuint32\fPsize, \fBfparams\fP &diffEq)"
Initializes \fBFilter\fP based on a difference equation\&.
.PP
\fBParameters:\fP
.RS 4
\fIdata\fP array to be filtered\&. The filtered data will be placed here\&.
.br
\fIsize\fP number of elements in the data array
.br
\fIdiffEq\fP a vector containing two vectors of float32's (a\&.k\&.a\&. singles, floats), that contains the numerator and denominator coefficients, respectively, of the z-domain tranfer function of the filter in decending order (z^0, z^-1, z^-2, etc\&.)\&. 
.RE
.PP

.PP
Definition at line 83 of file Filter\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void radio::Filter::Pass ()"
Passes the data array through the digital filter but does not account for previous x[n] and y[n] values from the previous call to \fBPass()\fP\&. 
.PP
Definition at line 90 of file Filter\&.hpp\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBfloat32\fP* radio::Filter::data\fC [protected]\fP"
A pointer to the start of the data array to be filtered when \fBPass()\fP is called\&. 
.PP
Definition at line 72 of file Filter\&.hpp\&.
.SS "\fBfparams\fP radio::Filter::diffEq\fC [protected]\fP"
A vector containing two vectors of float32's (a\&.k\&.a\&. singles, floats), containing the numerator and denominator coefficients, respectively, of the z-domain tranfer function of the filter in decending order (z^0, z^-1, z^-2, etc\&.)\&. 
.PP
Definition at line 80 of file Filter\&.hpp\&.
.SS "\fBuint8\fP radio::Filter::eqLength\fC [protected]\fP"
The number of terms in the numerator (or denomenator) of the transfer function (i\&.e\&., function order + 1)\&. 
.PP
Definition at line 61 of file Filter\&.hpp\&.
.SS "\fBuint32\fP radio::Filter::size\fC [protected]\fP"
The number of elements in the data array\&. 
.PP
Definition at line 66 of file Filter\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for An Inexpensive, Software-Defined IF Modulator from the source code\&.
