.TH "radio::Modulator" 3 "Sat Mar 5 2016" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
radio::Modulator \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <modulation\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBMod\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class, while not intended to be called directly, is a superclass for the classes of the modulation forms used in this project\&. 
.PP
Definition at line 35 of file modulation\&.hpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void radio::Modulator::Mod ()"
Modulates the audio currently in the data array\&. 
.PP
Definition at line 96 of file modulation\&.hpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
