.TH "This" 3 "Wed Apr 13 2016" "An Inexpensive, Software-Defined IF Modulator" \" -*- nroff -*-
.ad l
.nh
.SH NAME
This \- 
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
namespace contains all the classes, functions, and enumerations used in the application\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for An Inexpensive, Software-Defined IF Modulator from the source code\&.
