\hypertarget{makefile}{\section{makefile File Reference}
\label{makefile}\index{makefile@{makefile}}
}


Contains recipes to compile the main program and the tests programs as well as making documentation and counting total lines of code in src/.  




\subsection{Detailed Description}
Contains recipes to compile the main program and the tests programs as well as making documentation and counting total lines of code in src/. 

\begin{DoxyAuthor}{Author}
Samuel Andrew Wisner, \href{mailto:awisner94@gmail.com}{\tt awisner94@gmail.\+com} 
\end{DoxyAuthor}


Definition in file \hyperlink{makefile_source}{makefile}.

