radio
Age
Fractional
fparams radio::F_BASEBAND
Baseband filter coefficients.
Referenced by main.
void radio::aconj(cfloat32 *data, uint32 size)
Replaces the values in an array of complex float32's with their respective conjugates. data the array whose values should be replaced with their respective conjugates size the number of elements in the data array
Referenced by ifft.
void radio::fft(cfloat32 *data, uint32 size)
Replaces the values of an array of cfloat32's with the array's DFT using a decimation-in-frequency algorithm.This code is based on code from http://rosettacode.org/wiki/Fast_Fourier_transform#C.2B.2B. data the array whose values should be replaced with its DFT size the number of elements in the data array
Referenced by main, hilbert, ifft.
void radio::hilbert(float32 *data, float32 *dest, uint32 size)
Performs the hilbert transfor of an array of float32's. data the source array of the REAL numbers of which to take the Hilbert transform dest the destination array of REAL numbers for the results of the Hilbert transform size the number of elements in the data and dest arrays
References fft, ifft.
Referenced by main, makeIQ.
void radio::ifft(cfloat32 *data, uint32 size)
Replaces the values of an array of cfloat32's with the array's inverse DFT.This code is based on code from http://rosettacode.org/wiki/Fast_Fourier_transform#C.2B.2B. data the array whose values should be replaced with its inverse DFT size the number of elements in the data array
References aconj, fft.
Referenced by main, hilbert.
void radio::makeIQ(float32 *data, float32 *dest, uint32 size)
Produces an interleaved array of first an element from an original array of data and then an element from the original data's Hilbert transform. This function is intended to generate a two-channel output (I/Q output) for mixing applications. data the original data (left channel) dest the interleaved data (left channel original data, right channel transformed data) twice the size of the original data array size the number of elements in the data array (NOT in the destination array)
References hilbert.
Referenced by main.